### ISSUE TITLE
Removing the mutators in the credential classes

### ISSUE THREAD

**Issue by mfrost503** [mfrost503/Snaggle#20]
Now that the values are also injected into the constructor, we're going to be moving toward the preference of using that instead the verbose mutator interface. This will be a breaking a change, and part of major version 1.0.0 release.

**Comment by localheinz** [comment]
@mfrost503 

Since I ragequit today, I'm going to spend some more time on open source - if you like, we can work together on stuff!

**Comment by mfrost503** [comment]
@localheinz - sorry been traveling a bit and dealing with some weird life stuff. I love this idea :)

**Comment by localheinz** [comment]
@mfrost503 

No worries!
